@hostname = sidebar.cyscrm.com

@port = 80/api

@uuid = 1

@hash = 12

@id = 1

### login controller
GET http://{{hostname}}:{{port}}/login HTTP/1.1

###
GET http://{{hostname}}:{{port}}/sidebarlogin?type=1 HTTP/1.1

###
GET http://{{hostname}}:{{port}}/wxlogin?code=1&state=1 HTTP/1.1

### myinfo 
GET http://{{hostname}}:{{port}}/myInfo/detail HTTP/1.1


### public
GET http://{{hostname}}:{{port}}/public/addReadTime/{{uuid}} HTTP/1.1

###
GET http://{{hostname}}:{{port}}/public/article/{{hash}} HTTP/1.1

###
GET http://{{hostname}}:{{port}}/public/file/{{id}} HTTP/1.1

###
GET http://{{hostname}}:{{port}}/public/addReadTime/{{uuid}} HTTP/1.1

### init
GET http://{{hostname}}:{{port}}/init HTTP/1.1

### menu
GET http://{{hostname}}:{{port}}/menu/{{uuid}} HTTP/1.1

###
GET http://{{hostname}}:{{port}}/menu/list HTTP/1.1
Cookie: JSESSIONID=70B89B14D1CCC5A79CEB5B0A8A7D1963

###
GET http://{{hostname}}:{{port}}/menu/listMy HTTP/1.1
Cookie: JSESSIONID=70B89B14D1CCC5A79CEB5B0A8A7D1963

### permission 
GET http://{{hostname}}:{{port}}/permission/listMy HTTP/1.1
Cookie: JSESSIONID=70B89B14D1CCC5A79CEB5B0A8A7D1963

###
GET http://47.111.161.128/api/public/file/5ef2f0a374818e7f9d00afbc HTTP/1.1
Content-Type: 